### ISSUE TITLE
installing ZackAttack & Backtrack5 R3

### ISSUE THREAD

**Issue by LinuxSTAIN** [urbanesec/ZackAttack#57]
Zack please help me.. i cant get ZackAttack to work with backtrack5 R3.. Here is where i run into the problems...

root@bt:~/ZackAttack# ruby zackattack.rb
/usr/lib/ruby/1.9.2/rubygems.rb:779:in report_activate_error': Could not find RubyGem sqlite3 (= 1.3.6) (Gem::LoadError)
from /usr/lib/ruby/1.9.2/rubygems.rb:214:inactivate'
from /usr/lib/ruby/1.9.2/rubygems.rb:1082:in gem'
from internal:gem_prelude:213:inpush_gem_version_on_load_path'
from internal:gem_prelude:16:in gem'
from /root/ZackAttack/lib/zfdb.rb:7:in'
from /root/ZackAttack/clients/ews.rb:9:in require'
from /root/ZackAttack/clients/ews.rb:9:in'
from /root/ZackAttack/lib/zfclient.rb:6:in require'
from /root/ZackAttack/lib/zfclient.rb:6:in'
from /root/ZackAttack/lib/zfhttpd.rb:7:in require'
from /root/ZackAttack/lib/zfhttpd.rb:7:in'
from zackattack.rb:8:in require'
from zackattack.rb:8:in'

I did install sqlite3 and now i get this.....

root@bt:~/ZackAttack# ruby zackattack.rb
/usr/lib/ruby/1.9.2/rubygems.rb:779:in `report_activate_error': RubyGem version error: sqlite3(1.3.7 not = 1.3.6) (Gem::LoadError)
        from /usr/lib/ruby/1.9.2/rubygems.rb:214:in`activate'
        from /usr/lib/ruby/1.9.2/rubygems.rb:1082:in `gem'
        from <internal:gem_prelude>:213:in`push_gem_version_on_load_path'
        from internal:gem_prelude:16:in `gem'
        from /root/ZackAttack/lib/zfdb.rb:7:in`<top (required)>'
        from /root/ZackAttack/clients/ews.rb:9:in `require'
        from /root/ZackAttack/clients/ews.rb:9:in`<top (required)>'
        from /root/ZackAttack/lib/zfclient.rb:6:in `require'
        from /root/ZackAttack/lib/zfclient.rb:6:in`<top (required)>'
        from /root/ZackAttack/lib/zfhttpd.rb:7:in `require'
        from /root/ZackAttack/lib/zfhttpd.rb:7:in`<top (required)>'
        from zackattack.rb:8:in `require'
        from zackattack.rb:8:in`<main>

here is my gem query:

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.6)
actionpack (3.0.6)
activemodel (3.0.6)
activerecord (3.0.6)
activeresource (3.0.6)
activesupport (3.0.6)
addressable (2.3.2)
arel (2.0.9)
bson (1.5.2)
bson_ext (1.5.2)
builder (2.1.2)
bundler (1.0.13)
childprocess (0.3.5)
diff-lcs (1.1.2)
em-resolv-replace (1.1.2)
erubis (2.6.6)
factory_girl (1.3.3)
ffi (1.1.5)
fxruby (1.6.25)
hpricot (0.8.6)
http_configuration (1.0.4)
i18n (0.5.0)
json (1.7.4, 1.6.5)
libwebsocket (0.1.5)
mail (2.2.19)
mime-types (1.17.2, 1.16)
mini_exiftool (1.3.1)
mongo (1.5.2)
multi_json (1.3.6)
mysql (2.8.1)
nokogiri (1.4.4)
polyglot (0.3.1)
rack (1.2.2)
rack-mount (0.6.14)
rack-test (0.5.7)
rails (3.0.6)
railties (3.0.6)
rake (0.8.7)
rchardet (1.3)
RedCloth (4.2.5)
rspec (2.5.0)
rspec-core (2.5.2)
rspec-expectations (2.5.0)
rspec-mocks (2.5.0)
rspec-rails (2.5.0)
rubyzip (0.9.6.1)
selenium-webdriver (2.25.0)
spider (0.4.4)
sqlite3 (1.3.7)
sqlite3-ruby (1.2.5)
thor (0.14.6)
treetop (1.4.9)
typhoeus (0.3.3, 0.2.4)
tzinfo (0.3.27)
watobo (0.9.8.724)
xml-simple (1.1.1, 1.1.0)
zip (2.0.2)
root@bt:~# 

what am i doing wrong?
Could it be that its not installed in the right directory?? Please have patience with me i am learning a lot in a little amount of time

**Comment by zfasel** [comment]
The answer is obvious in the error messages (in fact, it's the first line). As i explained in email, I'm not going to assist any further since you emailed me from an overly phishy "Facebook Support" gmail address/name.
