### ISSUE TITLE
cant run on windows

### ISSUE THREAD

**Issue by ghost** [urbanesec/ZackAttack#59]
- RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x64-mingw32]
  - INSTALLATION DIRECTORY: D:/Ruby23-x64/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: C:/Users/Caleb/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: D:/Ruby23-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: D:/Ruby23-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Caleb/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
    - D:/Ruby23-x64/lib/ruby/gems/2.3.0
    - C:/Users/Caleb/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
    - :update_sources => true
    - :verbose => true
    - :backtrace => false
    - :bulk_threshold => 1000
  - REMOTE SOURCES:
    - https://rubygems.org/
  - SHELL PATH:
    - C:\Program Files\Common Files\Microsoft Shared\Windows Live
    - C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
    - C:\Program Files (x86)\AMD APP\bin\x86_64
    - C:\Program Files (x86)\AMD APP\bin\x86
    - C:\ProgramData\Oracle\Java\javapath
    - C:\Windows\system32
    - C:\Windows
    - C:\Windows\System32\Wbem
    - C:\Windows\System32\WindowsPowerShell\v1.0\
    - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
    - C:\Program Files (x86)\Windows Live\Shared
    - C:\WINDOWS\system32
    - C:\WINDOWS
    - C:\WINDOWS\System32\Wbem
    - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
    - C:\Program Files\nodejs\
    - C:\Program Files (x86)\Skype\Phone\
    - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    - C:\Program Files (x86)\Lua\5.1
    - C:\Program Files (x86)\Lua\5.1\clibs
    - C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
    - C:\Program Files\Microsoft SQL Server\110\Tools\Binn\
    - D:\Ruby23-x64\bin
    - C:\Program Files (x86)\Nmap
    - C:\Users\Caleb\AppData\Roaming\npm
    - D:\Program Files (x86)\Nmap

D:\zack attack>ruby zackattack.rb
D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'sqlite3' (= 1.3.6) - did find: [sqlite3-1.3.11-x64-mingw32] (Gem::LoadError)
Checked in 'GEM_PATH=C:/Users/Caleb/.gem/ruby/2.3.0;D:/Ruby23-x64/lib/ruby/gems/2.3.0', execute`gem env`for more information
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/dependency.rb:328:in`to_spec'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from D:/zack attack/lib/zfdb.rb:7:in`<top (required)>'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from D:/zack attack/clients/ews.rb:9:in`<top (required)>'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from D:/zack attack/lib/zfclient.rb:6:in`<top (required)>'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from D:/zack attack/lib/zfhttpd.rb:7:in`<top (required)>'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
        from D:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from zackattack.rb:8:in`<main>'

**Comment by ghost** [comment]
D:\zack attack>gem query --local

**\* LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
sqlite3 (1.3.11 x64-mingw32)
test-unit (3.1.5)

**Comment by zfasel** [comment]
![img](http://i.giphy.com/3o6ZsZKbgw4QVWEbzq.gif)

This is a "will not fix". Because of the SMB service needing 445 and windows being a PITA with disabling SMB, I'm not going to troubleshoot getting it to work on windows. There will be a fix for it to work seamlessly on the latest version of Kali soon.

**Comment by MoD01** [comment]
I have the same issue with Kali Linux on USBarmory (arm). Any suggestions how to circumvent this ?
```
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'sqlite3' (= 1.3.6) - did find: [sqlite3-1.3.13,sqlite3-1.3.9] (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/arm-linux-gnueabihf/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /root/ZackAttack/lib/zfdb.rb:7:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /root/ZackAttack/clients/ews.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /root/ZackAttack/lib/zfclient.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /root/ZackAttack/lib/zfhttpd.rb:7:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from zackattack.rb:8:in `<main>'
```

## Update:
fixed it by updating `lib/zfdb.rb` Line 7
`- gem 'sqlite3', '1.3.6' #wtf ruby 1.92`
`+ gem 'sqlite3', '1.3.9' #wtf ruby 1.92`
